version: '3.9'

services:
  postgres:
    container_name: postgres_container
    image: postgres:bullseye
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-change_me}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change_me}
      POSTGRES_DB: ${POSTGRES_DATABASE:-change_me}
    networks:
      - database
    ports:
      - "5432:5432"
    restart: always

networks:
  database:
    driver: bridge

volumes:
  postgres: {}