CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         TEXT                                    NOT NULL,
    phone_number TEXT                                    NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);